### ISSUE TITLE
Make it possible to pass environment variables to tox

### ISSUE THREAD

**Issue by mikicz** [fedora-python/tox-github-action#35]
Hello :wave: 

At my company we have private Python packages which we have in our private registry (AWS CodeArtififact specifically). To install these one must be authenticated. When using Poetry for dependency management, the easiest way to pass these credentials is environment variables (so for example `POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME` and `POETRY_HTTP_BASIC_CODEARTIFACT_INSTALL_PASSWORD`).

In a package I am working on, my dev dependencies are managed by poetry as well, so my tox looks like:

<details>
<summary>tox.ini</summary>

```
[tox]
envlist =
    py{311,312,313}

[gh]
python =
    "3.11" = py311
    "3.12" = py312
    "3.13" = py313

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync
commands =
    poetry run pytest tests/ --import-mode importlib

usedevelop = true
setenv =
    DJANGO_SETTINGS_MODULE = tests.testproject.settings
passenv =
    POETRY_HTTP_BASIC_CODEARTIFACT_INSTALL_PASSWORD
    POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME
```
</details>

This works fine locally to install the dependencies.

However, when I want to use this action, the environment variable can't be passed to tox, so I get an authentication error while installing dependencies...

This is how my action usage looks:
```
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: poetry
      env:
        POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME: aws
        POETRY_HTTP_BASIC_CODEARTIFACT_INSTALL_PASSWORD: ${{ steps.token.outputs.TOKEN }}
```

With this setup I get this error

```
py311: commands_pre[0]> poetry install --no-root --sync
Updating dependencies
Resolving dependencies...
Source (codeartifact-install): Authorization error accessing https://xelix-XXXXXX.d.codeartifact.eu-west-2.amazonaws.com/pypi/xelix/simple/XXXXXXXX/

Because XXXXXXXX depends on XXXXXXXX (>=2.2.0) which doesn't match any versions, version solving failed.
```

To me it looks like the issue is here, https://github.com/fedora-python/tox-github-action/blob/main/action.yaml#L20 - the environment variables are not being passed :confused: But not sure it's possible to pass them along?

Passing environment variables might not be the best way forward tbh, but I am not quite sure how else I should use this action to install packages from private repo - any other ideas on how to make it work?

**Comment by hroncok** [comment]
Hey @mikicz :)

Perhaps you can try something like:

```yaml
    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables
      run: echo -e "POETRY_HTTP_BASIC_CODEARTIFACT_USERNAME=aws\nPOETRY_HTTP_BASIC_CODEARTIFACT_INSTALL_PASSWORD=${{ steps.token.outputs.TOKEN }}" >> $GITHUB_ENV
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: poetry
```

I don't know if this works or not. I have never tried it, but I'd try it. See https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions and https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsstepsenv

----

If you don't mind asking: What is the point of running tox if you delegate everything in it to poetry?
